config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

covid_dwh:
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: clickhouse
      port: 8123
    ci:
      type: clickhouse
      host: clickhouse
      port: 8123
      schema: default
      threads: 4
  target: ci
